- name: copying compose file to ansible directory
  template:
    src: docker-compose_public.yml.j2
    dest: "docker-compose.yml"
    mode: "0644"
  when: mode_of_installation != "localhost"
  tags: [ install, update ]

- name: copying compose file to ansible directory
  template:
    src: docker-compose_localhost.yml.j2
    dest: "docker-compose.yml"
    mode: "0644"
  when: mode_of_installation == "localhost"
  tags: [ install, update ]
