base_dir: /opt
system_user_name: gitpod
access_type: VSK
state_name: HP
local_ipv4_address: 127.0.0.1
mode_of_installation: localhost
storage_type: local
api_endpoint: localhost
google_analytics_tracking_id: NA
db_user: cqube_user
db_name: cqube
db_password: cQube@123
keycloak_adm_name: admin
keycloak_adm_password: Admin@123
dashboard_default_username: Cqube
dashboard_default_password: Cqube@123
