---
- name: Upgradting cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  become: true
  vars_files:
    - ../config_files/upgradation_config.yml
    - ../config_files/upgradation_azure_container_config.yml
    - ../config_files/upgradation_aws_s3_config.yml
    - ../config_files/upgradation_local_storage_config.yml
    - ../config_files/upgradation_oracle_storage_config.yml
    - ../config_files/program_selector.yml
    - ../config_files/national_program_selector.yml
    - ../config_files/upgradation_oracle_storage_config.yml
    - ../.version

  roles:
          - configurations
          - python
          - keycloak
          - ingestion
          - spec
          - generator
          - dashboard
          - querybuilder
          - nifi
